fix:refactor compute and cloudshell credentials to pass quota project to base class
googleapis/google-auth-library-java pull request #1284
Opened 2023-09-13 20:04 UTC by sai-sunder-s

Currently quota project that is set in the builder is dropped when build() is called for cloudshell and gce creds because the constructors are not rolling up the builders upto the base class.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-auth-library-java/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

2023-10-02 01:32 UTC, TimurSadykov requested changes
Overall looks good, except margin visibility

2023-10-02 01:32 UTC, TimurSadykov commented on oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
> +    protected Duration refreshMargin = DEFAULT_REFRESH_MARGIN;
why this?

2024-01-10 18:39 UTC, sai-sunder-s commented on oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
> +    protected Duration refreshMargin = DEFAULT_REFRESH_MARGIN;
removed

2024-01-11 06:16 UTC, TimurSadykov requested changes
please add more tests

2024-01-11 06:16 UTC, TimurSadykov commented on oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
> +      return new CloudShellCredentials(this);
Can you please add a test  for this, similar to toBuilder_build in ComputeCredentialsTests?

2024-01-11 06:16 UTC, TimurSadykov commented on oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
> +    this.authPort = builder.getAuthPort();
Could you please test this as well? While it is partially covered in CredentialsProvider - we want to have coverage here as well. CredentialsProvider might someday go away or instantiate credentials differently.

2024-01-17 19:47 UTC, TimurSadykov approved these changes
LGTM, thanks!

2024-01-17 19:47 UTC, merged