feat: adds CAB rules classes
googleapis/google-auth-library-java pull request #687
Opened 2021-06-14 20:04 UTC by lsirac

Adds CAB rule classes (see go/cab-client)

2021-06-17 09:45 UTC, TimurSadykov requested changes

2021-06-17 09:45 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/CredentialAccessBoundaryTest.java
> +    assertEquals(secondRule, credentialAccessBoundary.getAccessBoundaryRules().get(1));
assert AvailabilityCondition is set in rule1 and not set in rule2?

2021-06-17 09:45 UTC, TimurSadykov commented on oauth2_http/java/com/google/auth/oauth2/CredentialAccessBoundary.java
> +        this.expression = checkNotNull(expression);
we don't want blank string here right? Maybe checkArgument(!StringUtils.isBlank(expression))?

2021-06-17 09:45 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/CredentialAccessBoundaryTest.java
> +      AvailabilityCondition.newBuilder().setExpression(null).build();
test for blank? (empty, whitespace)

2021-06-17 09:45 UTC, TimurSadykov commented on oauth2_http/java/com/google/auth/oauth2/CredentialAccessBoundary.java
> +     * An optional condition that can be used as part of a {@link CredentialAccessBoundary} to
Some details on what kind of expression it is, how it is used?

2021-06-17 09:45 UTC, TimurSadykov commented on oauth2_http/java/com/google/auth/oauth2/CredentialAccessBoundary.java
> +        /** */
remove empty?

2021-06-17 09:45 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/CredentialAccessBoundaryTest.java
> +        AvailabilityCondition.newBuilder().setExpression("expression").build();
Let's add title and description to make sure they make their way to json

2021-06-17 09:45 UTC, TimurSadykov commented on oauth2_http/java/com/google/auth/oauth2/CredentialAccessBoundary.java
> +  /** Defines an upper bound of permissions on a particular resource. */
elaborate with small example?

2021-06-17 11:03 UTC, elharo commented on oauth2_http/java/com/google/auth/oauth2/CredentialAccessBoundary.java
> +       * <p>e.g. "inRole:roles/storage.objectViewer".
nit: e.g. --> for example, per google tech writing guidelines

2021-06-17 11:03 UTC, elharo commented on oauth2_http/javatests/com/google/auth/oauth2/CredentialAccessBoundaryTest.java
> +import static org.junit.Assert.*;
google style does not allow wildcard imports

2021-06-18 18:02 UTC, elharo commented on oauth2_http/java/com/google/auth/oauth2/CredentialAccessBoundary.java
> +          "The list of provided availablePermissions is either null or empty.");
These should be two checks with two different messages. In general avoid messages like "Thing X is wrong or Thing Y is wrong" in favor of simply "Thing X is wrong"

2021-06-18 20:41 UTC, elharo commented on oauth2_http/java/com/google/auth/oauth2/CredentialAccessBoundary.java
> +import static com.google.common.base.Preconditions.*;
google style doesn't use wildcard imports

2021-06-18 20:41 UTC, elharo commented on oauth2_http/java/com/google/auth/oauth2/CredentialAccessBoundary.java
> +    checkArgument(accessBoundaryRules != null, "The provided list of accessBoundaryRules is null.");
Preconditions.checkNotNull

2021-06-19 11:14 UTC, elharo approved these changes

2021-06-21 18:46 UTC, TimurSadykov approved these changes
LGTM

2021-06-21 19:02 UTC, merged