fix: use source credential expiration when STS does not return expires_in
googleapis/google-auth-library-java pull request #699
Opened 2021-07-22 17:39 UTC by lsirac

For the CAB flow, STS only returns expires_in if the source access token belongs to a service account.
In that case, we can copy the source credentials expiration as the generated downscoped token
will always have the same expiration time as the source credentials.

2021-07-23 08:55 UTC, TimurSadykov requested changes

2021-07-23 08:55 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/DownscopedCredentialsTest.java
> +  public void refreshAccessToken_userCredentials_expectExpiresInCopied() throws IOException {
add doc explaining the behavior that you are trying to test... from PR description :)

2021-07-23 08:55 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/StsRequestHandlerTest.java
> +  public void exchangeToken_noExpiresInReturned() throws IOException {
Also document why expires_in might not be returned?

2021-07-26 21:10 UTC, lsirac commented on oauth2_http/java/com/google/auth/oauth2/DownscopedCredentials.java
> +      if (sourceAccessToken.getExpirationTime() != null) {
Yes. They should still be able to use the downscoped token (e.g. can consume via OAuth2Credentials).

2021-07-26 22:50 UTC, merged