fix: ImmutableSet converted to List for Impersonated Credentials
googleapis/google-auth-library-java pull request #732
Opened 2021-09-08 10:58 UTC by dpanangat

As part of BigQueryOptions or StorageOptions the SCOPES is defined as an ImmutableSet.
When using an Impersonated Account, it fails when trying to get service, as the SCOPES are immutableSet and the previous code tries to cast it to List directly and fails.
Adding a fix for the same.

Fixes #731 ☕️

2021-09-28 10:18 UTC, dpanangat commented
@googlebot I signed it!

2021-09-29 16:09 UTC, chingor13 requested changes
Thanks for submitting this. Can you add a simple test for this failure so that we don't regress in the future?

2022-02-03 07:53 UTC, TimurSadykov requested changes
Hi, sorry for delay, some minor comments and we can get it done. Thanks!

2022-02-03 07:53 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
> +import java.util.*;
Please keep individual imports

2022-02-03 07:53 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
> +
nit: please remove this empty line

2022-02-03 07:53 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
> +  private static final Set<String> IMMUTABLE_SCOPES = ImmutableSet.of("scope1","scope2");
please rename to IMMUTABLE_SCOPES_SET

2022-02-03 07:53 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
>    private static final List<String> SCOPES =
Please rename to IMMUTABLE_SCOPES_LIST

2022-03-03 10:31 UTC, dpanangat commented on oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
> +
removed this line

2022-03-10 03:17 UTC, TimurSadykov approved these changes
LGTM

2022-03-10 03:22 UTC, TimurSadykov commented
@dpanangat hey, thanks for updates, please fix the linter failure and we should be good to go. To do that you need to run the "mvn com.coveo:fmt-maven-plugin:format" command and push resulted format changes.

2022-03-15 19:06 UTC, chingor13 approved these changes

2022-03-15 23:46 UTC, merged