fix: remove erroneous check for the subject token field name for text credential source
googleapis/google-auth-library-java pull request #822
Opened 2022-01-06 22:47 UTC by lsirac

Fixes #815

2022-01-07 00:41 UTC, TimurSadykov commented on oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
> +        if ("json".equals(type)) {
why not using CredentialFormatType.JSON?

2022-01-07 00:42 UTC, TimurSadykov commented on oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
> +        if ("json".equals(type)) {
type.toLowerCase()?

2022-01-07 00:43 UTC, TimurSadykov commented on oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
> +        } else if ("text".equals(type)) {
similarly toLowerCase ?

2022-01-07 00:46 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
> +    jsonTextFormat.put("type", "json");
add uppercase letters? headers are case insensitive, but our code could be :)

2022-01-07 00:47 UTC, TimurSadykov requested changes
One small fix to make sure we support case insensitive headers

2022-01-07 22:00 UTC, Neenu1995 approved these changes

2022-01-08 05:22 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
> +import java.util.*;
this has to stay as separate imports, maybe owl bot fixes that

2022-01-08 05:28 UTC, TimurSadykov commented on oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
> +import java.util.*;
also should keep individual imports

2022-01-08 05:29 UTC, TimurSadykov approved these changes
LGTM, but please remove "star" imports

2022-01-10 19:35 UTC, merged