feat: Adds Pluggable Auth support to ADC
googleapis/google-auth-library-java pull request #895
Opened 2022-03-21 21:56 UTC by lsirac

Adds the ability to retrieve 3rd party tokens through user defined executables. 

See go/pluggable-auth-design.

The implementation for the handler will come in a separate PR.

2022-03-24 17:18 UTC, Neenu1995 approved these changes

2022-03-30 01:02 UTC, TimurSadykov requested changes
Hey, 

Went through the code, without tests for now. Will do another pass later. 
You will see many nits on grammar articles, sorry about that :) Please apply for the rest of the code. Basically, owners before me had a higher bar for docs, I'm trying to match them. My english could backfire for sure, so let me know if i'm incorrect somewhere.

2022-03-30 21:55 UTC, lsirac commented on oauth2_http/java/com/google/auth/oauth2/ExecutableHandler.java
> +    /** @return The timeout for waiting for the executable to finish, in milliseconds. */
I think "The timeout..." makes more sense here

2022-03-30 22:01 UTC, lsirac commented on oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
> +    // workforcePoolUserProject must be passed to STS via the internal options param.
This is fixed with the merge.

2022-03-30 22:02 UTC, lsirac commented on oauth2_http/java/com/google/auth/oauth2/PluggableAuthCredentials.java
> +      // TODO(lsirac): Initialize handler.
Yes. Will come in the next PR.

2022-03-30 22:08 UTC, lsirac commented on oauth2_http/java/com/google/auth/oauth2/PluggableAuthCredentials.java
> +   * Encapsulates the credential source portion of the configuration for PluggableAuthCredentials.
See above comment

2022-03-30 22:09 UTC, lsirac commented on oauth2_http/java/com/google/auth/oauth2/PluggableAuthCredentials.java
> +    // The default timeout for waiting for the executable to finish (30 seconds).
It is "The executable" as it is a definite article

2022-04-04 21:55 UTC, merged