#992 Not loosing the access token when calling UserCredentials#ToBuil…
googleapis/google-auth-library-java pull request #993
Opened 2022-09-07 13:05 UTC by qcastel

Fixes #992 ☕️

2022-09-08 05:27 UTC, TimurSadykov requested changes
Thanks for the contribution! Few minor comments.

2022-09-08 05:27 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
> +  public void toBuilder() throws IOException {
Please rename similarly to other tests, so the name describes what is being tested and expected behavior. 
Like UserCredentians_ToBuilder_AccessTokenSaved

2022-09-08 05:27 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
> +    credentials.toBuilder().build();
This line is not needed?

2022-09-08 06:29 UTC, qcastel commented
@TimurSadykov As I was making the test a little bit more generic than just checking the access token, I found out that two methods of the builders were missing.
The test is now covering that every attributes of the credentials are copied over correctly during the ToBuilder()

2022-10-24 07:57 UTC, qcastel commented
@TimurSadykov any news on this one?

2022-10-26 10:54 UTC, TimurSadykov approved these changes
Sorry for a delay. 

LGTM, i will merge once the last nit is fixed.

2022-10-26 10:54 UTC, TimurSadykov commented on oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
> +  public void UserCredentials_ToBuilder_CopyEveryAttributes() {
nit, every part has to stat with lowercase, like this and a typo fix: userCredentials_toBuilder_copyEveryAttribute

2022-10-28 14:59 UTC, qcastel commented on oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
> +  public void UserCredentials_ToBuilder_CopyEveryAttributes() {
```suggestion
  public void userCredentials_toBuilder_copyEveryAttribute() {
```

2022-12-02 08:51 UTC, TimurSadykov approved these changes
LGTM

2022-12-02 09:03 UTC, merged